export const cardList = [
  {
    country: 'США',
    director: 'Дени Вильнёв',
    duration: 116,
    year: 2017,
    description: 'В недалеком будущем мир населен людьми и репликантами, созданными выполнять самую тяжелую работу. Работа офицера полиции Кей — держать репликантов под контролем в условиях нарастающего напряжения. Он случайно становится обладателем секретной информации, которая ставит под угрозу существование всего человечества.',
    image: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1946459/1430e241-feec-40d2-ba9f-19598e9d6ef1/1920x',
    trailerLink: 'https://link.ru',
    thumbnail: 'https://link.ru',
    movieId: 1,
    nameRU: 'Бегущий по лезвию 2049',
    nameEN: "Blade Runner 2049",
  },
  {
    country: 'США',
    director: 'Грета Гервиг',
    duration: 120,
    year: 2023,
    description: 'Барби выгоняют из Барбиленда, потому что она не соответствует его нормам красоты. Тогда она начинает новую жизнь в реальном мире, где обнаруживает, что совершенства можно достичь только благодаря внутренней гармонии.',
    image: 'https://avatars.dzeninfra.ru/get-zen_doc/10118391/pub_64bfcc1335798b1a61a93273_64c03da640a38d7707ec54d2/scale_1200',
    trailerLink: 'https://link.ru',
    thumbnail: 'https://link.ru',
    movieId: 2,
    nameRU: 'Барби',
    nameEN: "Barbie",
  },
  {
    country: 'США',
    director: 'Гай Ричи',
    duration: 110,
    year: 2019,
    description: 'Один ушлый американец ещё со студенческих лет приторговывал наркотиками, а теперь придумал схему нелегального обогащения с использованием поместий обедневшей английской аристократии и очень неплохо на этом разбогател.',
    image: 'https://pic.rutubelist.ru/video/9c/e5/9ce537c862468b08e8e22506613415c0.jpg',
    trailerLink: 'https://link.ru',
    thumbnail: 'https://link.ru',
    movieId: 3,
    nameRU: 'Джентльмены',
    nameEN: "The Gentlemen",
  },
];

export const saveCardList = [
  {
    country: 'США',
    director: 'Дени Вильнёв',
    duration: 116,
    year: 2017,
    description: 'В недалеком будущем мир населен людьми и репликантами, созданными выполнять самую тяжелую работу. Работа офицера полиции Кей — держать репликантов под контролем в условиях нарастающего напряжения. Он случайно становится обладателем секретной информации, которая ставит под угрозу существование всего человечества.',
    image: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1946459/1430e241-feec-40d2-ba9f-19598e9d6ef1/1920x',
    trailerLink: 'https://link.ru',
    thumbnail: 'https://link.ru',
    movieId: 1,
    nameRU: 'Бегущий по лезвию 2049',
    nameEN: "Blade Runner 2049",
  },
  {
    country: 'США',
    director: 'Грета Гервиг',
    duration: 120,
    year: 2023,
    description: 'Барби выгоняют из Барбиленда, потому что она не соответствует его нормам красоты. Тогда она начинает новую жизнь в реальном мире, где обнаруживает, что совершенства можно достичь только благодаря внутренней гармонии.',
    image: 'https://avatars.dzeninfra.ru/get-zen_doc/10118391/pub_64bfcc1335798b1a61a93273_64c03da640a38d7707ec54d2/scale_1200',
    trailerLink: 'https://link.ru',
    thumbnail: 'https://link.ru',
    movieId: 2,
    nameRU: 'Барби',
    nameEN: "Barbie",
  },
];
